### PR TITLE
display human friendly error when no latest post is in database

### PR DESCRIPTION
**Pull request by ghost**
Thanks for the project, looks very nice and was easy to setup, really cool stuff!
I noticed there is an internal error when trying to call the LATEST post route when there is no post in the database:   
 
Before:
Screenshot From 2024-11-16 21-12-39
After:
Screenshot From 2024-11-16 21-38-01

I've added a error page similar to the 404, feel free to change the text. Also I fixed a small typo while I was at it.

### CODE REVIEW

**Comment by Pineapple217** [comment]
@TimHi Glad to see you like my project
I have looked at your code and made some [changes](https://github.com/TimHi/mb/pull/1). Good catch, this project really lacks some proper testing, some mistakes like that do creep in.

**Comment by ghost** [comment]
Cheers, thanks for the quick response! Your changes look way better 👍

**Comment by Pineapple217** [comment]
Alright, this is my  first pull request but I think you need to add my code to your branch now and add it to this PR so I can merge it into main

**Comment by ghost** [comment]
Done, looks good now

**Pull request merged**
